name: CI

on:
  pull_request: {}
  push: { branches: [ main ] }

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.0.6'
          distribution: temurin

      - name: Setup Gradle Build Action
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle Build
        run: ./gradlew check --scan --no-daemon -i
